import { User } from '../../../domain/entities';
import { CreateUserDto } from '../../../application/dto';

export class UserMapper {
    static toDomain(createUserDto: CreateUserDto): User {
        // Note: ID and dates are typically generated by the entity or DB
        // This is a simplified mapper request -> domain
        return new User(
            crypto.randomUUID(),
            createUserDto.name,
            createUserDto.email,
            createUserDto.password || '', // Password should be hashed in use case
            new Date(),
            new Date()
        );
    }

    static toResponse(user: User): any {
        return {
            id: user.id,
            name: user.name,
            email: user.email,
            createdAt: user.createdAt,
        };
    }
}
